# An env for re/building a Fortran pymt-lab component with Meson.
name: fbld
channels:
  - conda-forge
dependencies:
  - python =3
  - pip
  - make
  # - bmi-fortran =1.2.1
  - gipl
  - fortran-compiler
  - c-compiler
  - cxx-compiler
  - cython
  - pkg-config
  - meson-python
  - ninja
  - numpy
  - bmi-tester >=0.5.5
  - pymt >=1.3.2
